booking/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import permission_required

import booking.views as views

urlpatterns = [
    url(r'search/$', views.SearchView.as_view(), name='search'),
    url(r'search/results$', views.SearchResultsView.as_view(), name='search_results'),
    url(r'order/create$', views.OrderCreateView.as_view(), name='order_create'),
    url(r'order/create/success$', views.OrderCreateSuccessView.as_view(), name='order_create_success'),

    # Orders out
    url(r'orders/out/active', views.OutActiveOrdersView.as_view(), name='orders_out_active_list'),
    url(r'orders/out/completed', views.OutCompletedOrdersView.as_view(), name='orders_out_completed_list'),
    url(r'order/(?P<pk>[0-9]+)/cancel', views.order_cancel, name='order_cancel'),
    url(r'order/(?P<pk>[0-9]+)/confirmation/(?P<order_room_id>[0-9]+)', views.order_confirmation, name='order_confirmation'),

    # Orders in
    url(r'orders/in/active',
        permission_required('hotels.can_book_property', raise_exception=True)(views.InActiveOrdersView.as_view()),
        name='orders_in_active_list'),
    url(r'orders/in/completed',
        permission_required('hotels.can_book_property', raise_exception=True)(views.InCompletedOrdersView.as_view()),
        name='orders_in_completed_list'),
]

hh/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from users.views import PasswordChangeRedirectView
from hh.views import ContactFormView

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
    url(r'users/profile/password$', auth_views.password_change, {
        'template_name': 'users/password_change_form.html'},
        name='password_change'),
    url(r'users/profile/password/done$', PasswordChangeRedirectView.as_view(), name='password_change_done'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^booking/', include('booking.urls', namespace="booking")),
    url(r'^payments/', include('payments.urls', namespace="payments")),
    url(r'^hotels/', include('hotels.urls', namespace="hotel")),
    url(r'^$', RedirectView.as_view(pattern_name='booking:search', permanent=True), name='index'),
    url(r'^pages/contacts/', ContactFormView.as_view(), name='envelope-contact'),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotels/urls.py
from django.contrib.auth.decorators import permission_required
from django.conf.urls import url

import hotels.views as views

urlpatterns = [
    url(r'properties/$', permission_required('hotels.add_property', raise_exception=True)(views.PropertyList.as_view()),
        name='property_list'),
    url(r'property/add$',
        permission_required('hotels.add_property', raise_exception=True)(views.PropertyCreate.as_view()),
        name='property_create'),
    url(r'property/(?P<pk>[0-9]+)/change',
        permission_required('hotels.change_property', raise_exception=True)(views.PropertyUpdate.as_view()),
        name='property_change'),
    url(r'property/(?P<pk>[0-9]+)/rooms$',
        permission_required('hotels.add_room', raise_exception=True)(views.RoomList.as_view()),
        name='property_room_list'),
    url(r'property/(?P<pk>[0-9]+)/rooms/add$',
        permission_required('hotels.add_room', raise_exception=True)(views.RoomCreate.as_view()),
        name='property_room_create'),
    url(r'property/room/(?P<pk>[0-9]+)/change$',
        permission_required('hotels.change_room', raise_exception=True)(views.RoomUpdate.as_view()),
        name='property_room_change'),
    url(r'property/(?P<pk>[0-9]+)/photos$',
        permission_required('hotels.add_propertyphoto', raise_exception=True)(views.PhotoList.as_view()),
        name='property_photo_list'),
    url(r'property/photo/(?P<pk>[0-9]+)/delete$',
        permission_required('hotels.delete_propertyphoto', raise_exception=True)(views.PhotoDelete.as_view()),
        name='property_photo_delete'),
    url(r'property/(?P<pk>[0-9]+)/photos/add$',
        permission_required('hotels.add_propertyphoto', raise_exception=True)(views.PhotoCreate.as_view()),
        name='property_photo_create'),
    url(r'property/photo/(?P<pk>[0-9]+)/change$',
        permission_required('hotels.change_propertyphoto', raise_exception=True)(views.PhotoUpdate.as_view()),
        name='property_photo_change'),
]

payments/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import permission_required
import payments.views as views

urlpatterns = [
    url(
        r'^$', permission_required('payments.add_payment', raise_exception=True)(views.PaymentsListView.as_view()),
        name='payments_list'),
    url(
        r'add/funds$', permission_required('payments.add_payment', raise_exception=True)(views.AddFundsView.as_view()),
        name='add_funds'),
    url(
        r'add/funds/(?P<pk>[0-9]+)/pay',
        permission_required('payments.add_payment', raise_exception=True)(views.BillingFormView.as_view()),
        name='billing_form'),
    url(r'check/payment', views.check_payment, name='check_payment')
]

users/urls.py
from django.conf.urls import url
import users.views as views


urlpatterns = [
    url(r'profile$', views.Profile.as_view(), name='profile'),
    url(r'profile/edit$', views.UserUpdate.as_view(), name='profile_edit'),
    url('partner/add$', views.PartnershipOrderCreate.as_view(), name='partner_add'),
    url('messages$', views.get_messages, name='messages')
]

hh/models.py
import pytz
from django.contrib import messages
from django.db import models
from sitetree.models import TreeItemBase, TreeBase
from cities_light.abstract_models import AbstractCity, AbstractRegion, AbstractCountry
from cities_light.receivers import connect_default_signals
from django.utils.translation import ugettext_lazy as _
from geoposition.fields import GeopositionField


class DeleteSuccessMessageMixin(object):
    """
    Adds a success message on successful object deletion.
    """
    success_message = ''

    def delete(self, request, *args, **kwargs):
        success_message = self.success_message
        if success_message:
            messages.success(self.request, success_message)
        return super(DeleteSuccessMessageMixin, self).delete(request, *args, **kwargs)


class GeoMixin(models.Model):
    """
    GeoMixin: add Latitude & Longitude fields
    """
    position = GeopositionField(null=True, blank=True, verbose_name=_('coordinates'))
    latitude = models.DecimalField(max_digits=8, decimal_places=5, null=True, blank=True)
    longitude = models.DecimalField(max_digits=8, decimal_places=5, null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.position:
            self.latitude = self.position.latitude
            self.longitude = self.position.longitude
        super(GeoMixin, self).save(*args, **kwargs)

    class Meta:
        abstract = True


class CommonInfo(models.Model):
    """ CommonInfo abstract model """

    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, null=True, blank=True, editable=False)
    created_by = models.ForeignKey('users.User', null=True, blank=True, on_delete=models.CASCADE,
                                   related_name="%(app_label)s_%(class)s_created_by")
    modified_by = models.ForeignKey('users.User', null=True, blank=True, on_delete=models.CASCADE, editable=False,
                                    related_name="%(app_label)s_%(class)s_modified_by")

    def __str__(self):
        return getattr(self, 'name', '{} #{}'.format(type(self).__name__, str(self.id)))

    class Meta:
        abstract = True


class CityMixin:
    """
    City, Region, County name mixin
    """
    def get_first_alternate_name(self):
        """
        Returns first alternate name
        :return: string
        """
        return self.alternate_names.split(',')[0]
    get_first_alternate_name.short_description = 'Alternative name'
    get_first_alternate_name.admin_order_field = 'alternate_names'

    def __str__(self):
        name = self.get_first_alternate_name()
        return name if name else self.name


class Country(CityMixin, AbstractCountry):
    """ HH country model."""
    class Meta:
        ordering = ['name']
connect_default_signals(Country)


class Region(CityMixin, AbstractRegion):

    """ HH region model."""
    def get_display_name(self):
        return '%s, %s' % (self, self)

connect_default_signals(Region)


class City(CityMixin, AbstractCity):
    """ HH city model."""
    TIMEZONES = [(c, c) for c in pytz.all_timezones if c.startswith('Europe') or c.startswith('Asia')]

    timezone = models.CharField(
            max_length=40, null=True, blank=True, choices=TIMEZONES
    )
    sorting = models.IntegerField(default=0)
    is_enabled = models.BooleanField(default=False, verbose_name='Is enabled?')

    def get_display_name(self):
        if self.region_id:
            return '%s, %s, %s' % (self, self.region, self.country)
        else:
            return '%s, %s' % (self.name, self.country)

    @classmethod
    def get_with_hotels(cls):
        from hotels.models import Room
        ids = Room.objects.filter(is_enabled=True).values('property__city_id').distinct()
        return cls.objects.filter(is_enabled=True, id__in=ids)

    class Meta:
        ordering = ['-sorting', 'name']
        unique_together = (('region', 'name'), ('region', 'slug'))
        verbose_name_plural = _('cities')
connect_default_signals(City)


class SiteTreeTree(TreeBase):
    """ HH tree model."""
    pass


class SiteTreeItem(TreeItemBase):
    """ HH tree item model."""

    icon = models.CharField(max_length=50, null=True, blank=True, verbose_name='Иконка',
                            help_text='Иконка FontAwesome. Пример: fa-user.')

hh/forms.py
class FormInitialDataMixin:
    """
    Get initial data mixin
    """

    def get_initial_data(self, exclude=[]):
        return {key: field.initial for (key, field) in self.fields.items() if key not in exclude}

hh/views.py
from django.contrib.messages.views import SuccessMessageMixin
from envelope.views import ContactView


class ContactFormView(SuccessMessageMixin, ContactView):
    """
    Contacts form view
    """
    success_message = "Благодарим Вас за отправку письма! Наш специалист ответит Вам в ближайшее время."

hh/templates/partials/box_widget_begin.html
<div class="box box-{{ type|default:'default' }} box-solid">
    <div class="box-header">
        <h3 class="box-title">
            {{ header }}{% if smallHeader %}<small>{{ smallHeader }}</small>{% endif %}
        </h3>
        <div class="box-tools pull-right">
            <button class="btn btn-box-tool form-group-collapse" {% if id %}id="{{ id }}"{% endif %} data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="{{ class|default:'bg-gray-disabled color-palette' }} box-body">

hh/templates/partials/box_widget_end.html
</div></div>

hh/templates/partials/confirm_delete.html
{% extends 'layout.html' %}

{% block content %}
    <div class="box box-default">
        <div class="box-body">
            <form action="" method="post">
                {% csrf_token %}

                <button type="submit" class="btn btn-danger margin-right-md">
                    <i class="fa fa-trash"></i>
                   Вы точно хотите удалить {{ object }}?
                </button>
                <button type="button" onclick="history.go(-1);return false;"
                        class="btn btn-default">
                    <i class="fa fa-ban"></i>
                    <span class="hidden-xs margin-left-sm">Отмена</span>
                </button>

            </form>
        </div>
    </div>
{% endblock %}

hh/templates/partials/entry_buttons.html
{% load avatar %}
{% load humanize %}

<button type="submit" class="btn btn-success margin-right-sm">
    <i class="fa fa-check-circle-o"></i><span class="margin-left-sm">Save {{ title }}</span>
</button>
<a href="{% url list_url %}" class="btn btn-default">
    <i class="fa fa-ban"></i><span class="hidden-xs margin-left-sm">Cancel</span>
</a>
{% if entry and delete_permission %}
    <a href="{% url delete_url entry.id %}" class="btn btn-danger pull-right">
        <i class="fa fa-trash"></i><span class="hidden-xs margin-left-sm">Delete {{ title }}</span>
    </a>
{% endif %}

hh/templates/partials/header.html
{% load staticfiles %}
{% load humanize %}
{% load avatar %}
{% load has_group %}

<header class="main-header">
    <!-- Logo -->
    <a href="{% url 'index' %}" class="logo">
      <span class="logo-mini">
          <img src="{{ '/static/img/logo-hostelhunt-white.svg' }}" height="36">
      </span>
      <span class="logo-lg">
          <img id="hh-navbar-logo" src="{{ '/static/img/logo-hostelhunt-white.svg' }}" height="36">
          <b>Hostel</b>Hunt
      </span>
    </a>

    <nav class="navbar navbar-static-top" role="navigation">

        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <div class="navbar-custom-menu">
            {% if user.is_authenticated %}
                <ul class="nav navbar-nav">

                    {% if user.is_partner %}
                        <!-- Income -->
                        <li title="Входящие заявки" data-toggle="tooltip" data-placement="bottom" class="dropdown messages-menu margin-right-lg {{ request.incoming_orders|yesno:',opacity-half' }}">
                            <a href="{% url 'booking:orders_in_active_list' %}">
                                <i class="fa fa-phone"></i>
                                <span class="label label-{{ request.incoming_orders|yesno:'warning blink,default' }}">{{ request.incoming_orders }}</span>
                            </a>
                        </li>

                        <!-- Wallet balance -->
                        <li title="Балланс кошелька" data-toggle="tooltip" data-placement="bottom" class="dropdown messages-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-ruble"></i>
                                {% with balance=user.profile.wallet_balance %}
                                    <span class="label label-{% if balance > 0 %}success{% elif balance == 0 %}default{% else %}warning{% endif %}">{{ balance|intcomma }} р.</span>
                                {% endwith %}
                            </a>
                            <ul class="dropdown-menu">
                                {% with last_payments=user.get_last_payments %}
                                    {% if last_payments|length %}
                                        <li>
                                            <ul class="menu">
                                                {% for payment in last_payments %}
                                                    <li>
                                                        <a href="{% url 'payments:payments_list' %}?date_month={{ payment.created_at|date:'n' }}&date_year={{ payment.created_at|date:'Y' }}&payment_type=&is_send=1#payment{{ payment.id }}">
                                                            <strong class="text-{% if payment.total > 0 %}success{% else %}danger{% endif %}">{{ payment.total }}
                                                                р.</strong>
                                                            &nbsp;
                                                            <small class="text-muted">
                                                                #{{ payment.number }} от
                                                                {{ payment.created_at }}
                                                            </small>
                                                        </a>
                                                    </li>
                                                {% endfor %}
                                            </ul>
                                        </li>
                                    {% endif %}
                                {% endwith %}
                                <li class="footer"><a href="{% url 'payments:add_funds' %}">
                                    <i class="fa fa-plus margin-right-sm"></i>Пополнить балланс
                                </a></li>
                            </ul>
                        </li>

                    {% endif %}

                    <!-- User Account -->
                    <li class="dropdown user user-menu">
                        <a href="{% url 'users:profile' %}" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{% cached_avatar_url user 25 %}" class="user-image" alt="User avatar">
                            <span class="hidden-xs">{{ user }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="user-header">
                                <img src="{% cached_avatar_url user 160 %}" class="img-circle" alt="User avatar">
                                <p>
                                    {{ user }}
                                    {% if not user.is_partner %}
                                        <small>Начните зарабатывать сейчас! <a href="{% url 'users:partner_add' %}">Станьте
                                            партнером</a></small>
                                    {% else %}
                                        <small>Зарегистрировался {{ user.date_joined|naturalday }}</small>
                                    {% endif %}
                                </p>
                            </li>
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="{% url 'users:profile' %}" class="btn btn-default btn-flat">
                                        <i class="fa fa-user margin-right-sm"></i>Профиль
                                    </a>
                                </div>
                                <div class="pull-right">
                                    <a href="{% url 'account_logout' %}" class="btn btn-default btn-flat">
                                        <i class="fa fa-sign-out margin-right-sm"></i>Выйти
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav">
                <li class="user user-menu">
                        <a href="{% url 'account_login' %}">
                            <i class="fa fa-sign-in"></i> <strong>Войти</strong>
                        </a>
                </li>
                <li class="user user-menu">
                        <a href="{% url 'account_signup' %}">
                            <i class="fa fa-plus"></i> Регистрация
                        </a>
                </li>
                </ul>
            {% endif %}
        </div>
    </nav>
</header>

hh/templates/partials/messages.html
<div id="hh-messages">
    {% for message in messages %}
        <div class="alert callout {% if message.tags %} callout-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}{% endif %} alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&#215;</button>
            {{ message|safe }}
        </div>
    {% endfor %}
</div>

hh/templates/partials/modal_messages.html
<div class="modal fade" id="messages-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">×</span></button>
                <h4 class="modal-title">
                    Информация
                </h4>
            </div>
            <div class="modal-body main-background">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
            </div>
        </div>
    </div>
</div>

hh/templates/partials/notifications.html
<!-- Notifications -->
{% if request.user.is_hotelier and not request.user.hotels_property_created_by.all.count %}
    <div class="alert alert-warning">
        <i class="fa fa-info-circle"></i>
        У Вас еще не добавлено ни одного отеля. Перейти к <a href="{% url 'hotel:property_list' %}">управлению отелями?</a>
    </div>
{% endif %}

hh/templates/partials/sidebar.html
{% load sitetree %}

<aside class="main-sidebar">
    <section class="sidebar">
        {% if user.is_authenticated %}
            {% sitetree_menu from 'navbar' include "trunk" template "sitetree/menu_bootstrap3.html" %}
        {% else %}
            <ul class="sidebar-menu">
                <li class="header">ВХОД</li>
                <li>
                    <a href="{% url 'account_login' %}">
                        <i class="fa fa-sign-in"></i><span>Войти</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'account_signup' %}">
                        <i class="fa fa-plus"></i><span>Регистрация</span>
                    </a>
                </li>
            </ul>
        {% endif %}
    </section>
</aside>

hh/templates/partials/thead.html
{% load url_replace %}

<thead>
<tr>
    {% for th in thead %}
        <th class="{{ th.class }}">
            {% if th.sort %}
                {% if request.GET.sort == th.sort %}
                    <small>
                        <i class="fa fa-sort-amount-{{ request.GET.order }} margin-right-sm"></i>
                    </small>
                {% endif %}
                {% if request.GET.order == 'asc' and request.GET.sort == th.sort %}
                    <a href="{% url link %}?{% url_replace request sort=th.sort order='desc' %}">
                {% else %}
                    <a href="{% url link %}?{% url_replace request sort=th.sort order='asc' %}">
                {% endif %}
            {{ th.title|title }}
            </a>

            {% else %}
                {{ th.title|title }}
            {% endif %}
        </th>
    {% endfor %}
    <th class="td-sm text-right"></th>
</tr>
</thead>