booking/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import permission_required

import booking.views as views

urlpatterns = [
    url(r'search/$', views.SearchView.as_view(), name='search'),
    url(r'search/results$', views.SearchResultsView.as_view(), name='search_results'),
    url(r'order/create$', views.OrderCreateView.as_view(), name='order_create'),
    url(r'order/create/success$', views.OrderCreateSuccessView.as_view(), name='order_create_success'),

    # Orders out
    url(r'orders/out/active', views.OutActiveOrdersView.as_view(), name='orders_out_active_list'),
    url(r'orders/out/completed', views.OutCompletedOrdersView.as_view(), name='orders_out_completed_list'),
    url(r'order/(?P<pk>[0-9]+)/cancel', views.order_cancel, name='order_cancel'),
    url(r'order/(?P<pk>[0-9]+)/confirmation/(?P<order_room_id>[0-9]+)', views.order_confirmation, name='order_confirmation'),

    # Orders in
    url(r'orders/in/active',
        permission_required('hotels.can_book_property', raise_exception=True)(views.InActiveOrdersView.as_view()),
        name='orders_in_active_list'),
    url(r'orders/in/completed',
        permission_required('hotels.can_book_property', raise_exception=True)(views.InCompletedOrdersView.as_view()),
        name='orders_in_completed_list'),
]

hh/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from users.views import PasswordChangeRedirectView
from hh.views import ContactFormView

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
    url(r'users/profile/password$', auth_views.password_change, {
        'template_name': 'users/password_change_form.html'},
        name='password_change'),
    url(r'users/profile/password/done$', PasswordChangeRedirectView.as_view(), name='password_change_done'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^booking/', include('booking.urls', namespace="booking")),
    url(r'^payments/', include('payments.urls', namespace="payments")),
    url(r'^hotels/', include('hotels.urls', namespace="hotel")),
    url(r'^$', RedirectView.as_view(pattern_name='booking:search', permanent=True), name='index'),
    url(r'^pages/contacts/', ContactFormView.as_view(), name='envelope-contact'),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/models.py
from datetime import date
from django.db import models
from django.conf import settings
from django.utils.timezone import timedelta, now
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField
from hh.models import CommonInfo
from hotels.models import Room


class OrderManager(models.Manager):
    """
    OrderManager manager
    """
    def user_can_booking(self, user):
        """
        Check user order limit
        :param user
        """
        if not user.is_authenticated():
            return False

        query = self.all().filter(created_by=user)

        if query.count() and not user.is_partner():
            last_order = query.latest('created_at')
            time_limit = settings.HH_BOOKING_ORDER_TIME_LIMIT
            if last_order.created_at + timedelta(minutes=time_limit) > now():
                return False

        limit = settings.HH_BOOKING_ORDER_PARTNER_LIMIT if user.is_partner() else settings.HH_BOOKING_ORDER_USER_LIMIT
        if query.filter(status='process').count() >= limit:
            return False

        return True

    def filter_for_hotelier(self, user, query=None):
        """
        Filter Orders for hotelier
        :param user: user
        :type user: user.User
        :param query: query
        :type query: QuerySet or None
        :return: filtered QuerySet
        :rtype: QuerySet
        """
        if query is None:
            query = self.all()
        hotels = user.hotels_property_created_by.all()

        return query.filter(order_rooms__room__property__in=hotels).distinct()


def get_order_ends_at_datetime():
    return now() + timedelta(minutes=settings.HH_BOOKING_ORDER_LIFETIME)


class Order(CommonInfo):
    """
    Booking order class
    """
    CITIZENSHIP_TYPES = (
        ('rus', 'Россия'),
        ('sng', 'СНГ'),
        ('eu', 'Европа'),
        ('usa', 'США'),
        ('other', 'Другое')

    )
    STATUSES = (
        ('process', 'Обрабатывается'),
        ('completed', 'Принята'),
        ('canceled', 'Отменена')

    )
    STATUSES_INFO = {
        'process': {'icon': 'fa fa-spin fa-spinner', 'class': 'default'},
        'completed': {'icon': 'fa fa-check', 'class': 'success'},
        'canceled': {'icon': 'fa fa-ban', 'class': 'danger'}
    }

    PERCENT_VALIDATORS = [MaxValueValidator(100)]

    objects = OrderManager()
    original_status = None

    first_name = models.CharField(max_length=50, verbose_name=_('first name'))
    last_name = models.CharField(max_length=50, verbose_name=_('last name'))
    patronymic = models.CharField(max_length=50, null=True, blank=True, verbose_name=_('patronymic'))
    citizenship = models.CharField(
            max_length=100, choices=CITIZENSHIP_TYPES, default='rus', verbose_name=_('citizenship')
    )
    phone = PhoneNumberField(max_length=30, verbose_name=_('mobile phone'))
    email = models.EmailField(max_length=100, null=True, blank=True, verbose_name=_('e-mail'))
    begin = models.DateField(verbose_name=_('Check-in'))
    end = models.DateField(verbose_name=_('Check-out'))
    places = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(20)])
    total = models.PositiveIntegerField(null=True, blank=True, validators=[MinValueValidator(1)], verbose_name=_('total'))
    commission = models.PositiveIntegerField(
            default=0, validators=PERCENT_VALIDATORS, verbose_name=_('commission'))
    agent_commission = models.PositiveIntegerField(
            default=0, validators=PERCENT_VALIDATORS, verbose_name=_('agent commission'))
    is_agent_order = models.BooleanField(default=False)
    status = models.CharField(max_length=20, choices=STATUSES, default='process', verbose_name=_('status'))
    accepted_room = models.ForeignKey(
            Room, null=True, blank=True, verbose_name=_('room'), related_name='%(class)s_accepted_room'
    )
    comment = models.TextField(null=True, blank=True, verbose_name=_('comment'))
    ends_at = models.DateTimeField(
            verbose_name=_('ends at'),
            default=get_order_ends_at_datetime)

    def __init__(self, *args, **kwargs):
        super(Order, self).__init__(*args, **kwargs)
        self.original_status = self.status

    def get_fio(self):
        """
        Get full name
        :return: full name string string
        """
        return '{} {} {}'.format(self.last_name, self.first_name, self.patronymic)
    get_fio.short_description = 'fio'

    def get_commission_sum(self):
        """
        Get commission sum
        :return: int
        """
        if self.total:
            return int(self.total * self.commission / 100)
        return 0
    get_commission_sum.short_description = 'commission sum'

    def get_agent_commission_sum(self):
        """
        Get agent commission sum
        :return: int
        """
        return int(self.get_commission_sum() * self.agent_commission / 100)
    get_agent_commission_sum.short_description = 'agent commission sum'

    def get_duration(self):
        """
        :return (int) duration in days or None
        """
        if self.end and self.begin:
            return (self.end - self.begin).days
        return None

    def get_property(self):
        """
        Get accepted room property
        :return: hotels.model.Property
        """
        if self.accepted_room:
            return self.accepted_room.property
        return None
    get_property.short_description = 'property'

    def get_full_name(self):
        return '{0} {1} {2}'.format(self.last_name, self.first_name, self.patronymic)

    def get_status_info(self):
        """
        Return status dict for order
        """
        return self.STATUSES_INFO[self.status]

    @property
    def can_cancel(self):
        """
        :return: can cancel order or not
        :rtype: boolean
        """
        return self.begin >= date.today()

    def clean(self):
        if self.begin and self.end and (self.begin > self.end):
            raise ValidationError('Dates incorrect')

        if self.begin and self.end and self.begin == self.end:
            self.end = self.begin + timedelta(days=1)

    class Meta:
        ordering = ['-created_at', 'status']


class OrderRoom(models.Model):
    """
    Booking order room class
    """
    room = models.ForeignKey(Room, verbose_name=_('room'))
    total = models.PositiveIntegerField(validators=[MinValueValidator(1)], verbose_name=_('total'))
    order = models.ForeignKey(Order, verbose_name=_('order'), related_name='order_rooms')
    is_accepted = models.BooleanField(default=False, verbose_name=_('is accepted'))

    def get_property(self):
        return self.room.property
    get_property.short_description = 'property'

    def delete(self, *args, **kwargs):
        if self.is_accepted:
            raise Exception('Cannot delete accepted room')
        super(OrderRoom, self).delete(*args, **kwargs)

    def save(self, *args, **kwargs):
        super(OrderRoom, self).save(*args, **kwargs)

        if self.is_accepted and not self.order.accepted_room:
            self.order.accepted_room = self.room
            self.order.save()

    class Meta:
        ordering = ['-is_accepted']

booking/forms.py
import datetime
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MinValueValidator
from django_select2.forms import ModelSelect2Widget, ModelSelect2MultipleWidget
from hh.models import City
from hotels.models import MetroStation, Room, Property
from booking.models import Order
from hh.widgets.month import MonthYearWidget
from hh.forms import FormInitialDataMixin


def get_datetime_now():
    return datetime.datetime.now()


class OrdersFilterForm(forms.Form, FormInitialDataMixin):
    date = forms.DateField(
        widget=MonthYearWidget(attrs={'required': 'true'}), initial=get_datetime_now, label=_('Period'))
    status = forms.ChoiceField(choices=[['', '----------']] + list(Order.STATUSES)[1:],
                               required=False, label=_('status').capitalize())
    is_send = forms.CharField(widget=forms.HiddenInput, initial=1)


class CityWithHotelsWidget(ModelSelect2Widget):
    queryset = City.get_with_hotels()
    search_fields = [
        'name__icontains', 'alternate_names__icontains'
    ]
    attrs = {'class': 'not-select2'}


class MetroWithHotelsWidget(ModelSelect2MultipleWidget):
    queryset = MetroStation.get_with_hotels()
    search_fields = [
        'name__icontains',
    ]
    attrs = {'class': 'not-select2'}


class OrderPersonForm(forms.ModelForm):
    """
    Person form for order
    """
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'patronymic', 'phone', 'email', 'citizenship', 'comment']
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 4}),
        }


class SearchForm(forms.Form):
    """
    Hotels search form
    """
    begin = forms.DateField(
        label=_('Check-in'), initial=get_datetime_now, widget=forms.DateInput(attrs={'required': 'true'}))

    end = forms.DateField(
        label=_('Check-out'), initial=lambda: get_datetime_now() + datetime.timedelta(days=1),
        widget=forms.DateInput(attrs={'required': 'true'}))

    places = forms.IntegerField(
        initial=1, widget=forms.NumberInput(attrs={'required': 'true', 'min': 1}),
        validators=[MinValueValidator(1)], label=_('Peoples'))

    city = forms.ModelChoiceField(
        queryset=City.get_with_hotels(), widget=CityWithHotelsWidget, initial=347, label=_('City'))

    metro_stations = forms.ModelMultipleChoiceField(queryset=MetroStation.get_with_hotels(),
                                                    widget=MetroWithHotelsWidget, required=False, label=_('Metro'))

    type = forms.ChoiceField(choices=(('', '----------'),) + Property.TYPES,
                               required=False, label=_('Type'))

    gender = forms.ChoiceField(choices=(('', '----------'),) + Room.GENDER_TYPES[1:],
                               required=False, label=_('Gender'))

    def clean(self):
        cleaned_data = super(SearchForm, self).clean()
        begin = cleaned_data.get("begin")
        end = cleaned_data.get("end")

        if begin and end and (begin > end or begin < datetime.date.today()):
            raise forms.ValidationError("Dates incorrect")

        if begin == end:
            cleaned_data['end'] = begin + datetime.timedelta(days=1)

        return cleaned_data

booking/templates/booking/layout.html
{% extends 'layout.html' %}
{% load staticfiles %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'booking/css/search.css' %}">
    <link rel="stylesheet" href="{% static 'booking/css/orders.css' %}">
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'booking/js/search.js' %}"></script>
    <script src="{% static 'booking/js/orders.js' %}"></script>
    <script src="{% static 'js/metro.js' %}"></script>
{% endblock %}

{% block content %}
    {% block booking_content %}{{ block.super }}{% endblock %}
{% endblock %}

booking/templates/booking/order_confirmation_success.html
Заявка #{{ order.id }} успешно подтверждена.
<a href="{% url 'booking:orders_in_completed_list' %}#order{{ order.id }}">
    Перейти к заявке в архиве?
</a>
<br><br>
<strong>Заказчик: {{ order.get_full_name }}, {{ order.phone }}, {{ order.email }}</strong>

booking/templates/booking/order_info.html
{% load humanize %}
<td>
    <a name="order{{ order.id }}"></a>
    <h3 class="text-info">
        {% with status_info=order.get_status_info %}
            <small class="label label-{{ status_info.class }} margin-right-sm">#{{ order.id }}</small>
            <br class="hidden-sm hidden-md hidden-lg margin-bottom-sm">
            {{ order.begin }} - {{ order.end }} на {{ order.places }} чел.
            <small class="text-{{ status_info.class }}">
                <i class="{{ status_info.icon }}"></i> {{ order.get_status_display|lower }}
            </small>
        {% endwith %}
    </h3>
    <p class="text-muted font-lg">
        <small><i class="fa fa-male margin-right-sm"></i></small>
        {% if not incoming or order.accepted_room.property.created_by == request.user %}
            {{ order.get_full_name }}, {{ order.phone }}, {{ order.email }},
        {% else %}
            <span {% if order.status == 'processing' %} class="dashed-bottom" data-toggle="tooltip" data-placement="top"
                                                        title="Данные гостя появятся после подтвержедния заявки."{% endif %}>Данные гостя скрыты</span>
            ,
        {% endif %}
        {{ order.get_citizenship_display }}
    </p>
    {% if order.comment %}
        <div class="bg-gray disabled color-palette padding-all-sm margin-bottom-md">
            <small>{{ order.comment|linebreaks }}</small>
        </div>
    {% endif %}

    {% if order.status != 'process' and order.total %}
        <div class="bg-navy disabled color-palette padding-all-sm margin-bottom-md">
            <small class="margin-right-sm">Итого:</small>
            <strong class="font-lg margin-right-md">{{ order.total|intcomma }} руб.</strong>
            {% if order.is_agent_order and  order.agent_commission and order.created_by == request.user %}
                <div class="hidden-sm hidden-md hidden-lg margin-bottom-sm"></div>
                <small class="margin-right-sm">Заработок:</small>
                <strong class="font-lg">{{ order.get_agent_commission_sum|intcomma }} руб.</strong>
            {% endif %}
        </div>
    {% endif %}

    {% if order.status == 'process' or order.status == 'completed' %}
        <p class="text-danger">
            {% if order.status == 'process' %}
                <i class="fa fa-clock-o"></i> Заканчивается <span class="order-ends-at">{{ order.ends_at|date:'Y/m/d H:i:s'}}</span>
                <br class="hidden-sm hidden-md hidden-lg margin-bottom-sm">
            {% endif %}
            {% if order.created_by == request.user and not incoming and order.can_cancel %}
                <strong class="margin-left-sm"><a href="{% url 'booking:order_cancel' pk=order.id %}"
                            class="modal-confirm">Отменить заявку?</a></strong>
            {% endif %}
        </p>
    {% endif %}

    <div class="bg-gray padding-all-md color-palette">
        {% if not order.accepted_room %}
            <ul class="ul-st">
                {% for order_room in order.order_rooms.all %}
                    {% if not incoming or incoming and order_room.room.property.created_by == request.user %}
                        <li>
                            {% if incoming and order.status == 'process' %}
                                <button data-toggle="modal" data-target="#order-confirmation-form-modal"
                                        data-url="{% url 'booking:order_confirmation' pk=order.id order_room_id=order_room.id %}"
                                        class="btn btn-success btn-xs margin-right-sm order-confirmation-link"
                                        data-total="{{ order_room.total }}">
                                    <i class="fa fa-check"></i><span class="hidden-xs"> принять гостей</span>
                                </button>
                            {% endif %}
                            {{ order_room.room.property }} -
                            <small>
                                {{ order_room.room }} за {{ order_room.total|intcomma }} руб.
                            </small>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% else %}
            {% with property=order.accepted_room.property room=order.accepted_room %}
                <h4>
                    «{{ property }}»
                    <small>{{ property.get_type_display }} -
                        {{ room }}
                        {{ property.phone }}
                    </small>
                </h4>
                <p>
                    {% if property.position %}
                        <a target="_blank" title="Посмотреть на карте" data-toggle="tooltip" data-placement="top"
                           href="http://maps.google.com/maps?q=loc:{{ property.position }}">
                            <i class="fa fa-map-marker margin-right-sm"></i>
                        </a>
                    {% else %}
                        <i class="fa fa-compass margin-right-sm"></i>
                    {% endif %}
                    {{ property.city }}, {{ property.address }}
                </p>
                <p>
                    <i class="fa fa-phone  margin-right-sm"></i>
                    {{ property.created_by.profile.phone }}
                </p>

            {% endwith %}
        {% endif %}
    </div>
    <div class="text-right margin-top-sm">
        <small>{{ order.created_at }}</small>
    </div>
</td>

booking/templates/booking/order_person_form.html
{% load crispy_forms_tags %}
{% csrf_token %}
{% crispy form %}

booking/templates/booking/order_person_form_error.html
<div class="alert alert-danger">
    <p>
        Во время создания заявки произошла непредвиденная ошибка.<br>
        Попробуйте перезагрузить страницу (кнопка F5) и попробовать снова.<br>
        Если ошибка повторится, обратитесь пожалуйста в службу поддержки HostelHunt.
    </p>
    {% include 'booking/partials/reload_message.html' %}
</div>

booking/templates/booking/order_person_form_success.html
<div class="alert alert-success">
    <p><i class="fa fa-check-circle"></i> Заявка успешно оформлена. Ожидайте ответа выбраных отелей.</p>
    {% include 'booking/partials/reload_message.html' %}
</div>

booking/templates/booking/orders_in_active_list.html
{% extends 'booking/orders_in_list_layout.html' %}

{% block order_out_list_content %}
    {% if object_list|length %}

        <form id="order-confirmation-form" action="" method="get">
        <!-- Order modal -->
        <div class="modal fade" id="order-confirmation-form-modal" tabindex="-1" role="dialog"
             aria-labelledby="order-form-modal">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">

                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">
                            Заполните форму для подтверждения заявки
                        </h4>
                    </div>

                    <div class="modal-body main-background">
                        <div class="bg-gray color-palette alert">

                            <p>
                                После подтверждения заявки отобразятся <strong>контактные данные заказчика</strong>,
                                необходимые для связи с ним.<br>
                                Если этого не произошло обратитесь в техническую поддержку HostelHunt.<br>
                            </p>
                            <p>
                                <strong>
                                    <i class="fa fa-info-circle"></i>
                                    Для продолжения необходимо заполнить окончательную сумму проживания гостя.
                                </strong>
                            </p>
                        </div>

                        <div class="box box-default">
                            <div class="box-body" id="order-form-modal-body">
                                <div class="alert alert-danger" style="display: none"; id="order-confirmation-total-error"></div>
                                <div id="div_order-confirmation-total" class="form-group">
                                    <label for="order_confirmation_total" class="control-label  requiredField">
                                        Cумма заказа<span class="asteriskField">*</span>
                                    </label>
                                    <div class="controls ">
                                        <input class="textinput textInput form-control"
                                               id="order-confirmation-total" min="0" max="999999999999999"
                                               name="order_confirmation_total" type="number" value="0" required>
                                        <span class="help-block">
                                            Окончательная сумма заказа.
                                            Сумма не может быть больше <span id="order-confirmation-total-help">0</span> руб.
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="overlay" id="order-confirmation-form-overlay" style="display: none;">
                                <i class="fa fa-refresh fa-spin"></i>
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                        <button type="submit" class="btn btn-success" id="send-order-confirmation-form">
                            <i class="fa fa-check"></i>
                            Подтвердить заявку
                        </button>
                    </div>
                </div>
            </div>
        </div>
        </form>

        <div class="text-right">
            <small class="text-muted">
                всего: {{ object_list|length }}
            </small>
        </div>
        <table class="table table-hover table-striped" id="out-active-orders-table">
            {% for order in object_list %}
                <tr>
                    {% include 'booking/order_info.html' with order=order incoming=True %}
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <div class="alert alert-info">
            <i class="fa fa-info-circle margin-right-xs"></i>
            У вас нет активных заявок.
        </div>
    {% endif %}
{% endblock %}

booking/templates/booking/orders_in_completed_list.html
{% extends 'booking/orders_in_list_layout.html' %}
{% load crispy_forms_filters %}
{% block tabs %}
    {% with 'completed' as tab %}{{ block.super }}{% endwith %}
{% endblock tabs %}

{% block order_out_list_content %}
    <div class="callout callout-warning">
        <form class="form-inline" action="" id="orders-filter-form" method="get">
                {% for field in filter_form %}
                    {{ field|as_crispy_field }}
                {% endfor %}
            <div class="form-group">
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-search"></i>
                    <span class="margin-left-sm">Показать</span>
                </button>
            </div>
        </form>
    </div>
    {% if object_list|length %}
        <div class="text-right">
            <small class="text-muted">
                всего: {{ object_list|length }}
            </small>
        </div>
        <table class="table table-hover table-striped" id="out-active-orders-table">
            {% for order in object_list %}
                <tr>
                    {% include 'booking/order_info.html' with order=order incoming=True %}
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <div class="alert alert-info">
            <i class="fa fa-info-circle margin-right-xs"></i>
            Заявки не найдены.</a>
        </div>
    {% endif %}
{% endblock %}

booking/templates/booking/orders_in_list_layout.html
{% extends 'booking/search.html' %}

{% block booking_content %}

    <div class="nav-tabs-custom">
        {% block tabs %}
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" {% if tab == 'active' or not tab %}class="active"{% endif %}>
                    <a href="{% url 'booking:orders_in_active_list' %}" aria-controls="home" role="tab">
                        <i class="fa fa-phone"></i> Активные
                    </a>
                </li>
                <li role="presentation" {% if tab == 'completed' %}class="active"{% endif %}>
                    <a href="{% url 'booking:orders_in_completed_list' %}" aria-controls="security" role="tab">
                        <i class="fa fa-clock-o"></i> Архив
                    </a>
                </li>
            </ul>
        {% endblock %}

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active margin-top-md-lg">
                {% block order_out_list_content %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

booking/templates/booking/orders_out_active_list.html
{% extends 'booking/orders_out_list_layout.html' %}

{% block order_out_list_content %}
    {% if object_list|length %}
        <div class="text-right">
            <small class="text-muted">
                всего: {{ object_list|length }}
            </small>
        </div>
        <table class="table table-hover table-striped" id="out-active-orders-table">
            {% for order in object_list %}
                <tr>
                    {% include 'booking/order_info.html' with order=order %}
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <div class="alert alert-info">
            <i class="fa fa-info-circle margin-right-xs"></i>
            У вас нет активных заявок. <a href="{% url 'booking:search' %}">Создать новую?</a>
        </div>
    {% endif %}
{% endblock %}

booking/templates/booking/orders_out_completed_list.html
{% extends 'booking/orders_out_list_layout.html' %}
{% load crispy_forms_filters %}
{% block tabs %}
    {% with 'completed' as tab %}{{ block.super }}{% endwith %}
{% endblock tabs %}

{% block order_out_list_content %}
    <div class="callout callout-warning">
        <form class="form-inline" action="" id="orders-filter-form" method="get">
                {% for field in filter_form %}
                    {{ field|as_crispy_field }}
                {% endfor %}
            <div class="form-group">
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-search"></i>
                    <span class="margin-left-sm">Показать</span>
                </button>
            </div>
        </form>
    </div>
    {% if object_list|length %}
        <div class="text-right">
            <small class="text-muted">
                всего: {{ object_list|length }}
            </small>
        </div>
        <table class="table table-hover table-striped" id="out-active-orders-table">
            {% for order in object_list %}
                <tr>
                    {% include 'booking/order_info.html' with order=order %}
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <div class="alert alert-info">
            <i class="fa fa-info-circle margin-right-xs"></i>
            Заявки не найдены.
        </div>
    {% endif %}
{% endblock %}

booking/templates/booking/orders_out_list_layout.html
{% extends 'booking/search.html' %}

{% block booking_content %}

    <div class="nav-tabs-custom">
        {% block tabs %}
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" {% if tab == 'active' or not tab %}class="active"{% endif %}>
                    <a href="{% url 'booking:orders_out_active_list' %}" aria-controls="home" role="tab">
                        <i class="fa fa-bell"></i> Активные
                    </a>
                </li>
                <li role="presentation" {% if tab == 'completed' %}class="active"{% endif %}>
                    <a href="{% url 'booking:orders_out_completed_list' %}" aria-controls="security" role="tab">
                        <i class="fa fa-clock-o"></i> Архив
                    </a>
                </li>
            </ul>
        {% endblock %}

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active margin-top-md-lg">
                {% block order_out_list_content %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}