hh/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from users.views import PasswordChangeRedirectView
from hh.views import ContactFormView

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
    url(r'users/profile/password$', auth_views.password_change, {
        'template_name': 'users/password_change_form.html'},
        name='password_change'),
    url(r'users/profile/password/done$', PasswordChangeRedirectView.as_view(), name='password_change_done'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^booking/', include('booking.urls', namespace="booking")),
    url(r'^payments/', include('payments.urls', namespace="payments")),
    url(r'^hotels/', include('hotels.urls', namespace="hotel")),
    url(r'^$', RedirectView.as_view(pattern_name='booking:search', permanent=True), name='index'),
    url(r'^pages/contacts/', ContactFormView.as_view(), name='envelope-contact'),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
import users.views as views


urlpatterns = [
    url(r'profile$', views.Profile.as_view(), name='profile'),
    url(r'profile/edit$', views.UserUpdate.as_view(), name='profile_edit'),
    url('partner/add$', views.PartnershipOrderCreate.as_view(), name='partner_add'),
    url('messages$', views.get_messages, name='messages')
]

hotels/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError
from colorful.fields import RGBColorField
from django.db.models import Q
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import Thumbnail, ResizeToCover
from hh.models import CommonInfo, GeoMixin
from users.models import City
from booking.calculation import calc_price


class MetroStation(CommonInfo, GeoMixin):
    """
    Metro stations
    """
    name = models.CharField(max_length=80)
    city = models.ForeignKey(City, null=True, blank=False, on_delete=models.SET_NULL)
    color = RGBColorField(null=True, blank=True)

    @classmethod
    def get_with_hotels(cls):
        ids = Room.objects.filter(is_enabled=True).values('property__metro_stations__id').distinct()
        return cls.objects.filter(id__in=ids)

    class Meta:
        ordering = ['city', 'name']


class Tariff(CommonInfo):
    """
    Hotel tariffs
    """

    def validate_is_default(is_default):
        if not is_default and not Tariff.objects.filter(is_default=True).count():
            raise ValidationError('One of the tariffs should be the default')

    name = models.CharField(max_length=80)
    is_default = models.BooleanField(default=False, verbose_name='Is default?', validators=[validate_is_default])
    minimal_commission = models.PositiveIntegerField()

    def get_element_for_sum(self, total):
        """
        Find element for sum
        :param total: sum
        :return: TariffElement
        """
        return TariffElement.objects.get_for_sum(self, total)

    def delete(self, *args, **kwargs):
        if self.is_default:
            raise Exception('Cannot delete default tariff')
        super(Tariff, self).delete(*args, **kwargs)


class TariffElementManager(models.Manager):
    """
    TariffElement manager
    """
    def get_for_sum(self, tariff, total):
        """
        Find element for sum
        :param tariff: Tariff
        :param total: sum
        :return: TariffElement
        """
        q = self.all().filter(tariff=tariff)
        # get element between sums
        el = q.filter(start_sum__lte=total, end_sum__gt=total).first()
        # get smallest element
        if not el:
            el = q.filter(end_sum__gt=total).order_by().order_by('start_sum').first()
        # get biggest element
        if not el:
            el = q.filter(end_sum__lt=total).order_by().order_by('-start_sum').first()
        return el


class TariffElement(models.Model):
    """
    Tariff element
    """
    PERCENT_VALIDATORS = [MaxValueValidator(100)]
    objects = TariffElementManager()

    start_sum = models.PositiveIntegerField()
    end_sum = models.PositiveIntegerField()
    commission = models.PositiveIntegerField(validators=PERCENT_VALIDATORS)
    agent_commission = models.PositiveIntegerField(validators=PERCENT_VALIDATORS)
    tariff = models.ForeignKey(Tariff, on_delete=models.CASCADE)

    def clean(self):
        if self.start_sum >= self.end_sum:
            raise ValidationError('Start sum cannot exceed end sum')

    class Meta:
        ordering = ['start_sum']


class Property(CommonInfo, GeoMixin):
    """
    Property class
    """
    TYPES = (
        ('hotel', 'отель'),
        ('hostel', 'хостел'),
        ('flat', 'квартира')
    )

    name = models.CharField(max_length=255, verbose_name=_('name'))
    description = models.TextField(null=True, blank=True,
                                   verbose_name=_('description'), help_text='Краткое описание отеля для поиска')
    address = models.TextField(verbose_name=_('address'))
    city = models.ForeignKey(City, on_delete=models.PROTECT, verbose_name=_('city'))
    metro_stations = models.ManyToManyField(MetroStation, blank=True, verbose_name=_('metro'),
                                            help_text='Ближайшие станции метро', related_name='metro_stations')
    tariff = models.ForeignKey(Tariff, null=True, blank=True, on_delete=models.SET_NULL)
    sorting = models.IntegerField(default=0)
    is_enabled = models.BooleanField(default=True, verbose_name=_('is enabled?'))
    type = models.CharField(max_length=20, default='hotel', choices=TYPES, verbose_name=_('type'))

    def get_tariff(self):
        if self.tariff:
            return self.tariff
        else:
            return Tariff.objects.filter(is_default=True).first()

    def get_main_photo(self):
        return self.propertyphoto_set.order_by().order_by('-is_default').first()

    def get_main_photo_thumbnail(self):
        photo = self.get_main_photo()
        if photo:
            return photo.thumbnail.url
        return '/static/img/no-image.gif'

    def get_metro_stations_as_string(self):
        return ', '.join([str(m) for m in self.metro_stations.all()])

    get_metro_stations_as_string.short_description = 'Metro stations'

    def get_absolute_url(self):
        return reverse('hotel:property_change', args=[str(self.id)])

    class Meta:
        permissions = (
            ("can_search_property", "Can search property"),
            ("can_book_property", "Can book property"),
            ("can_send_property_orders", "Can send orders to property"),
        )
        ordering = ['name', '-sorting']
        verbose_name_plural = 'properties'


class PropertyPhoto(CommonInfo):
    """
    Property photo class
    """
    name = models.CharField(max_length=255, null=True, blank=True, verbose_name=_('title'))
    is_default = models.BooleanField(default=False, verbose_name=_('is default?'))
    photo = ProcessedImageField(upload_to='hotels_property_photos',
                                processors=[ResizeToCover(600, 600, False)],
                                format='JPEG',
                                options={'quality': 90},
                                verbose_name=_('photo')
                                )
    thumbnail = ImageSpecField(source='photo',
                               processors=[Thumbnail(120, 120)],
                               format='JPEG',
                               options={'quality': 90})

    thumbnail_xs = ImageSpecField(source='photo',
                                  processors=[Thumbnail(30, 30)],
                                  format='JPEG',
                                  options={'quality': 90})

    preview_photo = ImageSpecField(source='photo',
                                   processors=[ResizeToCover(300, 300, False)],
                                   format='JPEG',
                                   options={'quality': 90})

    property = models.ForeignKey(Property, on_delete=models.CASCADE)

    def __str__(self):
        return self.name if self.name else 'фото #{}'.format(self.id)

    def get_absolute_url(self):
        return reverse('hotel:property_photo_change', args=[str(self.id)])

    class Meta:
        ordering = ['-is_default']


class RoomManager(models.Manager):
    """
    Rooms manager
    """

    def search(self, **kwargs):
        """
        Search for rooms
        :param kwargs: search params
        :return: models.QuerySet
        """
        q = self.all()

        if 'city' in kwargs and kwargs['city']:
            q = q.filter(property__city=kwargs['city'])

        if 'places' in kwargs and kwargs['places']:
            q = q.filter(places__gte=kwargs['places'])

        if 'type' in kwargs and kwargs['type']:
            q = q.filter(property__type=kwargs['type'])

        if 'metro_stations' in kwargs and kwargs['metro_stations'] and len(kwargs['metro_stations']):
            q = q.filter(property__metro_stations__in=kwargs['metro_stations'])

        if 'gender' in kwargs and kwargs['gender'] in ['male', 'female']:
            q = q.filter(Q(gender=kwargs['gender']) | Q(gender='mixed'))

        return q.filter(is_enabled=True, property__is_enabled=True, created_by__groups__name='Hotelier')\
            .order_by('-property__sorting', 'price').distinct() \
            .select_related('property', 'property__city', 'property__tariff') \
            .prefetch_related('property__propertyphoto_set', 'property__city__metrostation_set')


class Room(CommonInfo):
    """
    Property room class
    """
    CALCULATION_TYPES = (
        ('per_person', 'За человека'),
        ('per_room', 'За номер')

    )
    GENDER_TYPES = (
        ('mixed', 'Смешанный'),
        ('male', 'Мужской'),
        ('female', 'Женский'),

    )
    total = None
    """Room total price for period"""

    objects = RoomManager()
    name = models.CharField(max_length=255, verbose_name=_('room name'))
    description = models.TextField(null=True, blank=True,
                                   verbose_name=_('description'), help_text='Краткое описание номера для поиска')
    calculation_type = models.CharField(max_length=20, default='per_person',
                                        choices=CALCULATION_TYPES, verbose_name=_('calculation type'))
    places = models.PositiveSmallIntegerField(validators=[MaxValueValidator(20)],
                                              verbose_name=_('places'), help_text='Количество мест/кроватей в номере')
    gender = models.CharField(max_length=20, default='mixed',
                              choices=GENDER_TYPES, verbose_name=_('room gender type'))
    price = models.PositiveIntegerField(validators=[MinValueValidator(1)], verbose_name=_('price'))
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    is_enabled = models.BooleanField(default=True, verbose_name=_('is enabled?'))

    def calc_price(self, persons, duration=None, begin=None, end=None):
        """
        Calc room price for period
        :param persons: adults + children
        :param duration: days
        :param begin: datetime
        :param end: datetime
        :return: integer
        """

users/forms.py
from django import forms
from django_select2.forms import ModelSelect2Widget
from users.models import PartnershipOrder, Organization, City


class CityWidget(ModelSelect2Widget):
    queryset = City.objects.filter(is_enabled=True)
    search_fields = [
        'name__icontains', 'alternate_names__icontains'
    ]
    attrs = {'class': 'not-select2'}


class PartnershipOrderForm(forms.ModelForm):
    """
    Frontend PartnershipOrderForm
    """
    class Meta:
        model = PartnershipOrder
        fields = [
            'last_name', 'first_name', 'patronymic', 'type', 'phone', 'city', 'experience', 'comment'
        ]
        widgets = {
            'city': CityWidget(attrs={'class': 'not-select2'}),
            'comment': forms.Textarea(attrs={'rows': 3, 'cols': 15}),
        }


class OrganizationForm(forms.ModelForm):
    """
    Frontend OrganizationForm
    """
    class Meta:
        model = Organization
        fields = ['type', 'name']

users/views.py
from django.views.generic import TemplateView, UpdateView, RedirectView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.shortcuts import redirect
from django.http import JsonResponse
from users.forms import PartnershipOrderForm, OrganizationForm
from users.models import Organization, PartnershipOrder
from hh.messengers.messenger import Messenger


class PartnershipOrderCreate(TemplateView):
    """
    PartnershipOrder add view
    """
    template_name = 'users/add_partner.html'
    success_url = reverse_lazy('users:partner_add')

    def get_context_data(self, **kwargs):
        context = super(PartnershipOrderCreate, self).get_context_data(**kwargs)
        user = self.request.user
        context['not_completed_orders_count'] = PartnershipOrder.objects.filter(
                created_by=user, status__in=('new', 'in_work')
        ).count()
        order_form_initial = {'first_name': user.first_name, 'last_name': user.last_name}

        if user.get_profile():
            order_form_initial.update({
                'patronymic': user.profile.patronymic,
                'phone': user.profile.phone,
                'type': user.profile.type,
                'city': user.profile.city,
                'experience': user.profile.experience,
            })

        context['order_form'] = PartnershipOrderForm(
                prefix='order_form',
                initial=order_form_initial,

                data=self.request.POST if self.request.POST else None)
        context['organization_form'] = OrganizationForm(
                instance=user.profile.organization if user.get_profile() else None,
                prefix='organization_form',
                data=self.request.POST if self.request.POST else None
        )
        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        # Get organization from request
        if context['organization_form'].is_valid():
            new_organization = context['organization_form'].save(commit=False)
            organizations = Organization.objects.filter(name__iexact=new_organization.name, type=new_organization.type)

            if not organizations:
                new_organization.save()
                organization = new_organization
            else:
                organization = organizations[0]

        else:
            organization = None

        # Save order
        if context['order_form'].is_valid():
            order = context['order_form'].save(commit=False)
            order.organization = organization
            order.save()
            messages.success(
                    request,
                    'Заявка #{} успешно создана. Наши менеджеры свяжутся с Вами в ближайшее время'.format(
                            order.pk)
            )
            return redirect(self.success_url)
        else:
            messages.error(request, 'Во время создания заяки произошли ошибки, исправьте их и попробуйте снова')

        return self.render_to_response(context)


class PasswordChangeRedirectView(RedirectView):
    """
    Password change done redirect
    """
    permanent = False
    url = reverse_lazy('users:profile')

    def get_redirect_url(self, *args, **kwargs):
        messages.success(self.request, 'Пароль успешно сохранен.')

        return super(PasswordChangeRedirectView, self).get_redirect_url(*args, **kwargs)


class Profile(TemplateView):
    """
    Profile view
    """

    template_name = 'users/profile.html'


class UserUpdate(SuccessMessageMixin, UpdateView):
    """
    User update view
    """
    model = User
    fields = ['last_name', 'first_name']
    success_url = reverse_lazy('users:profile')
    success_message = "Профиль успешно сохранен"
    template_name = 'users/profile_edit.html'

    def get_object(self):
        return self.request.user


def get_messages(request):
    """
    Get user messages as json
    :param request: request
    :return: django.http.JsonResponse
    """
    return JsonResponse(
        Messenger.get_messages(user=request.user), safe=False
    )

users/templates/users/add_partner.html
{% extends 'users/profile_layout.html' %}
{% load crispy_forms_tags %}
{% load has_group %}
{% load staticfiles %}

{% block tabs %}
    {% with 'partner' as tab %}{{ block.super }}{% endwith %}
{% endblock tabs %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'users/js/partnership_orders.js' %}"></script>
    {{ order_form.media.js }}
{% endblock %}


{% block profile_content %}

    {% if not not_completed_orders_count %}

        {% if request.user.is_partner and not request.POST %}
            <table id="partner-info-table" class="table table-striped table-hover">
                <tr>
                    <th class="td-sm-md"><strong>ФИО:</strong></th>
                    <td>{{ user.get_full_name }}</td>
                </tr>
                <tr>
                    <th class="td-sm-md"><strong>Телефон:</strong></th>
                    <td>{{ user.profile.phone }}</td>
                </tr>
                <tr>
                    <th class="td-sm-md"><strong>Тип:</strong></th>
                    <td>{{ user.profile.get_type_display }}</td>
                </tr>
                <tr>
                    <th class="td-sm-md"><strong>Город:</strong></th>
                    <td>{{ user.profile.city }}</td>
                </tr>
                <tr>
                    <th class="td-sm-md"><strong>Ваш опыт:</strong></th>
                    <td>{{ user.profile.experience }}</td>
                </tr>
                <tr>
                    <th class="td-sm-md"><strong>Организация:</strong></th>
                    <td>{{ user.profile.organization }}</td>
                </tr>
            </table>
            <a href="{% url 'users:partner_add' %}" class="btn btn-success" id="show-partner-add-form">
                <i class="fa fa fa-pencil-square-o margin-right-sm"></i>Редактировать
            </a>
        {% endif %}

        <form action="" method="post" id="partner-add-form"
              class="form {% if request.user.is_partner and not request.POST %}hidden{% endif %}">
            {% csrf_token %}
            <fieldset>
                <legend>Контактная информация</legend>
                {{ order_form|crispy }}
            </fieldset>
            <fieldset>
                <legend>Ваша организация</legend>
                {{ organization_form|crispy }}
            </fieldset>

            <button type="submit" class="btn btn-success margin-right-sm">
                <i class="fa fa-check-circle-o"></i><span class="margin-left-sm">Отправить заявку</span>
            </button>
            <a href="{% url 'users:partner_add' %}" class="btn btn-default">
                <i class="fa fa-ban"></i><span class="hidden-xs margin-left-sm">Отмена</span>
            </a>
        </form>

    {% else %}
        <div class="bg-gray disabled color-palette alert">
            <i class="fa fa-info-circle"></i>
            Ваша заявка ожидает обработки. Наши менеджеры свяжутся с Вами в ближайшее время.
        </div>
    {% endif %}
{% endblock %}

users/templates/users/layout.html
{% extends 'layout.html' %}

users/templates/users/password_change_form.html
{% extends 'users/profile_layout.html' %}
{% load crispy_forms_tags %}

{% block tabs %}
    {% with 'security' as tab %}{{ block.super }}{% endwith %}
{% endblock tabs %}

{% block profile_content %}

    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success margin-right-sm">
            <i class="fa fa-check-circle-o"></i><span class="margin-left-sm">Обновить пароль</span>
        </button>
        <a href="{% url 'users:profile' %}" class="btn btn-default">
            <i class="fa fa-ban"></i><span class="hidden-xs margin-left-sm">Отмена</span>
        </a>
    </form>

{% endblock %}

users/templates/users/profile.html
{% extends 'users/profile_layout.html' %}
{% load humanize %}

{% block profile_content %}

    <table class="table table-striped table-hover">
        <tbody>
        <tr>
            <th class="td-sm-md"><strong>Логин:</strong></th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th class="td-sm-md"><strong>Фамилия:</strong></th>
            <td>{{ user.last_name|default:'нет' }}</td>
        </tr>
        <tr>
            <th class="td-sm-md"><strong>Имя:</strong></th>
            <td>{{ user.first_name|default:'нет' }}</td>
        </tr>
        <tr>
            <th class="td-sm-md"><strong>E-mail:</strong></th>
            <td>{{ user.email|default:'нет' }}</td>
        </tr>
        </tbody>
    </table>
    <a href="{% url 'users:profile_edit' %}" class="btn btn-success">
        <i class="fa fa fa-pencil-square-o margin-right-sm"></i>Редактировать
    </a>
{% endblock %}

users/templates/users/profile_edit.html
{% extends 'users/profile_layout.html' %}
{% load crispy_forms_tags %}

{% block profile_content %}

    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success margin-right-sm">
            <i class="fa fa-check-circle-o"></i><span class="margin-left-sm">Сохранить</span>
        </button>
        <a href="{% url 'users:profile' %}" class="btn btn-default">
            <i class="fa fa-ban"></i><span class="hidden-xs margin-left-sm">Отмена</span>
        </a>
    </form>
{% endblock %}

users/templates/users/profile_layout.html
{% extends 'users/layout.html' %}
{% load humanize %}
{% load avatar_tags %}
{% load staticfiles %}
{% load has_group %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'users/css/profile.css' %}">
{% endblock %}

{% block content %}

    <div class="nav-tabs-custom">
        {% block tabs %}
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" {% if tab == 'profile' or not tab %}class="active"{% endif %}>
                    <a href="{% url 'users:profile' %}" aria-controls="home" role="tab">
                        <i class="fa fa-user"></i> Профиль
                    </a>
                </li>
                <li role="presentation" class="{{ request.user.is_partner|yesno:",tab-important" }}{% if tab == 'partner' %} active{% endif %}">
                    <a href="{% url 'users:partner_add' %}" aria-controls="security" class="text-danger">
                        <i class="fa fa-rub"></i> {{ request.user.is_partner|yesno:"Партнерство,Станьте партнером" }}
                    </a>
                </li>
                <li role="presentation" {% if tab == 'emails' %}class="active"{% endif %}>
                    <a href="{% url 'account_email' %}" aria-controls="security">
                        <i class="fa fa-envelope"></i> E-mail
                    </a>
                </li>
                <li role="presentation" {% if tab == 'socialaccount' %}class="active"{% endif %}>
                    <a href="{% url 'socialaccount_connections' %}" aria-controls="security">
                        <i class="fa fa-users"></i> Социальные аккаунты
                    </a>
                </li>
                <li role="presentation" {% if tab == 'security' %}class="active"{% endif %}>
                    <a href="{% url 'password_change' %}" aria-controls="security">
                        <i class="fa fa-lock"></i> Безопасность
                    </a>
                </li>
                <li role="presentation" {% if tab == 'avatars' %}class="active"{% endif %}>
                    <a href="{% url 'avatar_change' %}" aria-controls="avatars">
                        <i class="fa fa-camera"></i> Аватар
                    </a>
                </li>
            </ul>
        {% endblock %}

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active margin-top-md-lg">
                    <div class="col-sm-3" id="profile-avatar-col">
                        <a href="{% url 'avatar_change' %}" data-toggle="tooltip" title="Управление аватарами"
                           data-placement="bottom">
                            <img src="{% avatar_url user 250 %}" class="img-responsive img-rounded hidden-xs">
                        </a>
                    </div>
                    <div class="col-sm-9">
                        {% block profile_content %}{% endblock %}
                    </div>
            </div>
        </div>
    </div>
{% endblock %}