hh/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from users.views import PasswordChangeRedirectView
from hh.views import ContactFormView

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
    url(r'users/profile/password$', auth_views.password_change, {
        'template_name': 'users/password_change_form.html'},
        name='password_change'),
    url(r'users/profile/password/done$', PasswordChangeRedirectView.as_view(), name='password_change_done'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^booking/', include('booking.urls', namespace="booking")),
    url(r'^payments/', include('payments.urls', namespace="payments")),
    url(r'^hotels/', include('hotels.urls', namespace="hotel")),
    url(r'^$', RedirectView.as_view(pattern_name='booking:search', permanent=True), name='index'),
    url(r'^pages/contacts/', ContactFormView.as_view(), name='envelope-contact'),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotels/urls.py
from django.contrib.auth.decorators import permission_required
from django.conf.urls import url

import hotels.views as views

urlpatterns = [
    url(r'properties/$', permission_required('hotels.add_property', raise_exception=True)(views.PropertyList.as_view()),
        name='property_list'),
    url(r'property/add$',
        permission_required('hotels.add_property', raise_exception=True)(views.PropertyCreate.as_view()),
        name='property_create'),
    url(r'property/(?P<pk>[0-9]+)/change',
        permission_required('hotels.change_property', raise_exception=True)(views.PropertyUpdate.as_view()),
        name='property_change'),
    url(r'property/(?P<pk>[0-9]+)/rooms$',
        permission_required('hotels.add_room', raise_exception=True)(views.RoomList.as_view()),
        name='property_room_list'),
    url(r'property/(?P<pk>[0-9]+)/rooms/add$',
        permission_required('hotels.add_room', raise_exception=True)(views.RoomCreate.as_view()),
        name='property_room_create'),
    url(r'property/room/(?P<pk>[0-9]+)/change$',
        permission_required('hotels.change_room', raise_exception=True)(views.RoomUpdate.as_view()),
        name='property_room_change'),
    url(r'property/(?P<pk>[0-9]+)/photos$',
        permission_required('hotels.add_propertyphoto', raise_exception=True)(views.PhotoList.as_view()),
        name='property_photo_list'),
    url(r'property/photo/(?P<pk>[0-9]+)/delete$',
        permission_required('hotels.delete_propertyphoto', raise_exception=True)(views.PhotoDelete.as_view()),
        name='property_photo_delete'),
    url(r'property/(?P<pk>[0-9]+)/photos/add$',
        permission_required('hotels.add_propertyphoto', raise_exception=True)(views.PhotoCreate.as_view()),
        name='property_photo_create'),
    url(r'property/photo/(?P<pk>[0-9]+)/change$',
        permission_required('hotels.change_propertyphoto', raise_exception=True)(views.PhotoUpdate.as_view()),
        name='property_photo_change'),
]

hotels/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError
from colorful.fields import RGBColorField
from django.db.models import Q
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import Thumbnail, ResizeToCover
from hh.models import CommonInfo, GeoMixin
from users.models import City
from booking.calculation import calc_price


class MetroStation(CommonInfo, GeoMixin):
    """
    Metro stations
    """
    name = models.CharField(max_length=80)
    city = models.ForeignKey(City, null=True, blank=False, on_delete=models.SET_NULL)
    color = RGBColorField(null=True, blank=True)

    @classmethod
    def get_with_hotels(cls):
        ids = Room.objects.filter(is_enabled=True).values('property__metro_stations__id').distinct()
        return cls.objects.filter(id__in=ids)

    class Meta:
        ordering = ['city', 'name']


class Tariff(CommonInfo):
    """
    Hotel tariffs
    """

    def validate_is_default(is_default):
        if not is_default and not Tariff.objects.filter(is_default=True).count():
            raise ValidationError('One of the tariffs should be the default')

    name = models.CharField(max_length=80)
    is_default = models.BooleanField(default=False, verbose_name='Is default?', validators=[validate_is_default])
    minimal_commission = models.PositiveIntegerField()

    def get_element_for_sum(self, total):
        """
        Find element for sum
        :param total: sum
        :return: TariffElement
        """
        return TariffElement.objects.get_for_sum(self, total)

    def delete(self, *args, **kwargs):
        if self.is_default:
            raise Exception('Cannot delete default tariff')
        super(Tariff, self).delete(*args, **kwargs)


class TariffElementManager(models.Manager):
    """
    TariffElement manager
    """
    def get_for_sum(self, tariff, total):
        """
        Find element for sum
        :param tariff: Tariff
        :param total: sum
        :return: TariffElement
        """
        q = self.all().filter(tariff=tariff)
        # get element between sums
        el = q.filter(start_sum__lte=total, end_sum__gt=total).first()
        # get smallest element
        if not el:
            el = q.filter(end_sum__gt=total).order_by().order_by('start_sum').first()
        # get biggest element
        if not el:
            el = q.filter(end_sum__lt=total).order_by().order_by('-start_sum').first()
        return el


class TariffElement(models.Model):
    """
    Tariff element
    """
    PERCENT_VALIDATORS = [MaxValueValidator(100)]
    objects = TariffElementManager()

    start_sum = models.PositiveIntegerField()
    end_sum = models.PositiveIntegerField()
    commission = models.PositiveIntegerField(validators=PERCENT_VALIDATORS)
    agent_commission = models.PositiveIntegerField(validators=PERCENT_VALIDATORS)
    tariff = models.ForeignKey(Tariff, on_delete=models.CASCADE)

    def clean(self):
        if self.start_sum >= self.end_sum:
            raise ValidationError('Start sum cannot exceed end sum')

    class Meta:
        ordering = ['start_sum']


class Property(CommonInfo, GeoMixin):
    """
    Property class
    """
    TYPES = (
        ('hotel', 'отель'),
        ('hostel', 'хостел'),
        ('flat', 'квартира')
    )

    name = models.CharField(max_length=255, verbose_name=_('name'))
    description = models.TextField(null=True, blank=True,
                                   verbose_name=_('description'), help_text='Краткое описание отеля для поиска')
    address = models.TextField(verbose_name=_('address'))
    city = models.ForeignKey(City, on_delete=models.PROTECT, verbose_name=_('city'))
    metro_stations = models.ManyToManyField(MetroStation, blank=True, verbose_name=_('metro'),
                                            help_text='Ближайшие станции метро', related_name='metro_stations')
    tariff = models.ForeignKey(Tariff, null=True, blank=True, on_delete=models.SET_NULL)
    sorting = models.IntegerField(default=0)
    is_enabled = models.BooleanField(default=True, verbose_name=_('is enabled?'))
    type = models.CharField(max_length=20, default='hotel', choices=TYPES, verbose_name=_('type'))

    def get_tariff(self):
        if self.tariff:
            return self.tariff
        else:
            return Tariff.objects.filter(is_default=True).first()

    def get_main_photo(self):
        return self.propertyphoto_set.order_by().order_by('-is_default').first()

    def get_main_photo_thumbnail(self):
        photo = self.get_main_photo()
        if photo:
            return photo.thumbnail.url
        return '/static/img/no-image.gif'

    def get_metro_stations_as_string(self):
        return ', '.join([str(m) for m in self.metro_stations.all()])

    get_metro_stations_as_string.short_description = 'Metro stations'

    def get_absolute_url(self):
        return reverse('hotel:property_change', args=[str(self.id)])

    class Meta:
        permissions = (
            ("can_search_property", "Can search property"),
            ("can_book_property", "Can book property"),
            ("can_send_property_orders", "Can send orders to property"),
        )
        ordering = ['name', '-sorting']
        verbose_name_plural = 'properties'


class PropertyPhoto(CommonInfo):
    """
    Property photo class
    """
    name = models.CharField(max_length=255, null=True, blank=True, verbose_name=_('title'))
    is_default = models.BooleanField(default=False, verbose_name=_('is default?'))
    photo = ProcessedImageField(upload_to='hotels_property_photos',
                                processors=[ResizeToCover(600, 600, False)],
                                format='JPEG',
                                options={'quality': 90},
                                verbose_name=_('photo')
                                )
    thumbnail = ImageSpecField(source='photo',
                               processors=[Thumbnail(120, 120)],
                               format='JPEG',
                               options={'quality': 90})

    thumbnail_xs = ImageSpecField(source='photo',
                                  processors=[Thumbnail(30, 30)],
                                  format='JPEG',
                                  options={'quality': 90})

    preview_photo = ImageSpecField(source='photo',
                                   processors=[ResizeToCover(300, 300, False)],
                                   format='JPEG',
                                   options={'quality': 90})

    property = models.ForeignKey(Property, on_delete=models.CASCADE)

    def __str__(self):
        return self.name if self.name else 'фото #{}'.format(self.id)

    def get_absolute_url(self):
        return reverse('hotel:property_photo_change', args=[str(self.id)])

    class Meta:
        ordering = ['-is_default']


class RoomManager(models.Manager):
    """
    Rooms manager
    """

    def search(self, **kwargs):
        """
        Search for rooms
        :param kwargs: search params
        :return: models.QuerySet
        """
        q = self.all()

        if 'city' in kwargs and kwargs['city']:
            q = q.filter(property__city=kwargs['city'])

        if 'places' in kwargs and kwargs['places']:
            q = q.filter(places__gte=kwargs['places'])

        if 'type' in kwargs and kwargs['type']:
            q = q.filter(property__type=kwargs['type'])

        if 'metro_stations' in kwargs and kwargs['metro_stations'] and len(kwargs['metro_stations']):
            q = q.filter(property__metro_stations__in=kwargs['metro_stations'])

        if 'gender' in kwargs and kwargs['gender'] in ['male', 'female']:
            q = q.filter(Q(gender=kwargs['gender']) | Q(gender='mixed'))

        return q.filter(is_enabled=True, property__is_enabled=True, created_by__groups__name='Hotelier')\
            .order_by('-property__sorting', 'price').distinct() \
            .select_related('property', 'property__city', 'property__tariff') \
            .prefetch_related('property__propertyphoto_set', 'property__city__metrostation_set')


class Room(CommonInfo):
    """
    Property room class
    """
    CALCULATION_TYPES = (
        ('per_person', 'За человека'),
        ('per_room', 'За номер')

    )
    GENDER_TYPES = (
        ('mixed', 'Смешанный'),
        ('male', 'Мужской'),
        ('female', 'Женский'),

    )
    total = None
    """Room total price for period"""

    objects = RoomManager()
    name = models.CharField(max_length=255, verbose_name=_('room name'))
    description = models.TextField(null=True, blank=True,
                                   verbose_name=_('description'), help_text='Краткое описание номера для поиска')
    calculation_type = models.CharField(max_length=20, default='per_person',
                                        choices=CALCULATION_TYPES, verbose_name=_('calculation type'))
    places = models.PositiveSmallIntegerField(validators=[MaxValueValidator(20)],
                                              verbose_name=_('places'), help_text='Количество мест/кроватей в номере')
    gender = models.CharField(max_length=20, default='mixed',
                              choices=GENDER_TYPES, verbose_name=_('room gender type'))
    price = models.PositiveIntegerField(validators=[MinValueValidator(1)], verbose_name=_('price'))
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    is_enabled = models.BooleanField(default=True, verbose_name=_('is enabled?'))

    def calc_price(self, persons, duration=None, begin=None, end=None):
        """
        Calc room price for period
        :param persons: adults + children
        :param duration: days
        :param begin: datetime
        :param end: datetime
        :return: integer
        """

hotels/forms.py
from django import forms
from users.forms import CityWidget
from hotels.models import Property, Room, PropertyPhoto


class PhotoForm(forms.ModelForm):
    """
    Frontend photo form
    """
    class Meta:
        model = PropertyPhoto
        fields = ['photo', 'name', 'is_default']


class RoomForm(forms.ModelForm):
    """
    Frontend room form
    """
    class Meta:
        model = Room
        fields = ['name', 'description', 'places', 'gender', 'calculation_type', 'price', 'is_enabled']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 5, 'cols': 15}),
        }


class PropertyForm(forms.ModelForm):
    """
    Frontend Property form
    """
    class Meta:
        model = Property
        fields = [
            'name', 'description', 'type', 'city', 'address', 'metro_stations', 'position', 'is_enabled'
        ]
        widgets = {
            'city': CityWidget(attrs={'class': 'not-select2'}),
            'description': forms.Textarea(attrs={'rows': 5, 'cols': 15}),
            'address': forms.Textarea(attrs={'rows': 2, 'cols': 15}),
        }

hotels/templates/hotels/layout.html
{% extends 'layout.html' %}
{% load staticfiles %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'hotels/css/property.css' %}">
{% endblock %}

{% block content %}
    <div class="box box-default">
        <div class="box-body">
            {% block hotel_content %}{{ block.super }}{% endblock %}
        </div>
    </div>
{% endblock %}

hotels/templates/hotels/photo_form.html
{% extends property.id|yesno:'hotels/property_tabs.html,hotels/layout.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'hotels/js/photo.js' %}"></script>
{% endblock %}

{% block tabs %}
    {% with 'photos' as tab %}{{ block.super }}{% endwith %}
{% endblock tabs %}

{% block hotel_content %}
    <form action="" enctype="multipart/form-data" method="post" class="form">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success margin-right-sm">
            <i class="fa fa-check-circle-o"></i><span class="margin-left-sm">
            {{ propertyphoto.id|yesno:'Обновить, Добавить' }} фото</span>
        </button>
        <a href="{% url 'hotel:property_photo_list' property.id %}" class="btn btn-default">
            <i class="fa fa-ban"></i><span class="hidden-xs margin-left-sm">Отмена</span>
        </a>
    </form>
{% endblock %}

hotels/templates/hotels/photo_list.html
{% extends 'hotels/property_tabs.html' %}
{% load staticfiles %}

{% block tabs %}
    {% with 'photos' as tab %}{{ block.super }}{% endwith %}
{% endblock tabs %}

{% block hotel_content %}
    {% if photos|length %}
        {% for photo in photos %}
            <div class="property-photo-list-link">
                <a class="fancybox" rel="gallery" title="{{ photo.name }}"
                   href="{{ photo.photo.url }}">
                    <img src="{{ photo.thumbnail.url }}" class="img-rounded"
                         data-toggle="tooltip"
                         data-placement="top" title="Посмотреть фото">
                </a>

                <div class="property-photo-list-actions">
                    <a href="{% url 'hotel:property_photo_change' photo.id %}" class="btn btn-success btn-xs" data-toggle="tooltip" data-placement="top"
                       title="Редактировать фото">
                        <i class="fa fa-pencil"></i>
                    </a>
                    <a href="{% url 'hotel:property_photo_delete' photo.id %}" class="btn btn-danger btn-xs"
                       data-toggle="tooltip" data-placement="top" title="Удалить фото">
                        <i class="fa fa-trash"></i>
                    </a>
                </div>
            </div>
        {% endfor %}
        <p class="text-center margin-top-md-lg">
            <a href="{% url 'hotel:property_photo_create' property.id %}" class="btn btn-primary">
                <i class="fa fa-plus"></i> Добавить новое фото
            </a>
        </p>
    {% else %}
        <div class="alert alert-warning">
            <i class="fa fa-exclamation-circle margin-right-xs"></i>
            Не загружено ни одно фото отеля. <a href="{% url 'hotel:property_photo_create' property.id %}">Добавить первое?</a>
        </div>
    {% endif %}
{% endblock %}

hotels/templates/hotels/property_edit.html
{% extends property.id|yesno:'hotels/property_tabs.html,hotels/layout.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'js/metro.js' %}"></script>
{% endblock %}

{% block scripts_cdn %}
    {{ form.media.js }}
    <script src="{% static 'js/position.js' %}"></script>
{% endblock %}

{% block hotel_content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success margin-right-sm">
            <i class="fa fa-check-circle-o"></i><span class="margin-left-sm">
            {{ property.id|yesno:'Обновить, Добавить' }} отель</span>
        </button>
        <a href="{% url 'hotel:property_list' %}" class="btn btn-default">
            <i class="fa fa-ban"></i><span class="hidden-xs margin-left-sm">Отмена</span>
        </a>
    </form>
{% endblock %}

hotels/templates/hotels/property_list.html
{% extends 'hotels/layout.html' %}
{% load staticfiles %}
{% block hotel_content %}
    <table class="table table-hover table-striped" id="property-table">
        {% for property in object_list %}
            <tr>
                <td width="120" class="hidden-xs">
                    <a href="{% url 'hotel:property_photo_list' property.id %}">
                        <img src="{{ property.get_main_photo_thumbnail }}" class="img-rounded"
                             data-toggle="tooltip"
                             data-placement="top" title="Перейти к фотогалерее отеля">
                    </a>
                </td>
                <td>
                    <a href="{% url 'hotel:property_change' property.id %}"
                       class="btn btn-success btn-sm pull-right action" data-toggle="tooltip"
                       data-placement="left"
                       title="Перейти к редактированию отеля">
                        <i class="fa fa-pencil"></i>
                    </a>

                    <h3>
                        <a href="{% url 'hotel:property_change' property.id %}" data-toggle="tooltip"
                           data-placement="top" title="Перейти к редактированию отеля">
                             «{{ property }}»
                        </a>
                        <small>{{ property.get_type_display }}</small>
                    </h3>

                    <p class="text-muted font-lg">
                        {% if property.position %}
                            <a target="_blank" title="Посмотреть на карте" data-toggle="tooltip" data-placement="top"
                               href="http://maps.google.com/maps?q=loc:{{ property.position }}">
                                <i class="fa fa-map-marker margin-right-xs"></i>
                            </a>
                        {% else %}
                            <i class="fa fa-compass margin-right-sm"></i>
                        {% endif %}


                        {{ property.city }}, {{ property.address }}. {{ property.get_metro_stations_as_string }}
                    </p>
                    <small class="text-muted">{{ property.description|truncatechars:800|linebreaks }}</small>

                    {% if not property.propertyphoto_set.count %}
                        <p class="text-warning">
                            <i class="fa fa-exclamation-circle"></i>
                            Не загружены фото отеля.
                            Перейти к <a href="{% url 'hotel:property_photo_list' property.id %}">управлению фото?</a>

                        </p>
                    {% endif %}

                    {% if not property.room_set.count %}
                        <p class="text-danger">
                            <strong>
                                <i class="fa fa-exclamation-circle"></i>
                                Не заполнены цены и номера у отеля.
                                Перейти к <a href="{% url 'hotel:property_room_list' property.id %}">управлению
                                ценами?</a>
                            </strong>
                        </p>
                    {% endif %}
                    {% if not property.is_enabled %}
                        <p class="text-danger">
                            <strong>
                                <i class="fa fa-exclamation-circle"></i>
                                Отель выключен.
                                Перейти к <a href="{% url 'hotel:property_change' property.id %}">управлению отелем?</a>
                            </strong>
                        </p>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>

    <p class="text-center margin-top-md-lg">
        <a href="{% url 'hotel:property_create' %}" class="btn btn-primary">
            <i class="fa fa-plus"></i> Добавить новый отель
        </a>
    </p>


{% endblock %}

hotels/templates/hotels/property_tabs.html
{% extends 'hotels/layout.html' %}
{% load staticfiles %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'hotels/css/property.css' %}">
{% endblock %}

{% block content %}

    <div class="nav-tabs-custom">
        {% block tabs %}
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" {% if tab == 'property' or not tab %}class="active"{% endif %}>
                    <a href="{% url 'hotel:property_change' property.id %}" aria-controls="home" role="tab">
                        <i class="fa fa-home"></i> Отель
                    </a>
                </li>
                <li role="presentation" class="{% if tab == 'prices' %}active{% endif %}">
                    <a href="{% url 'hotel:property_room_list' property.id %}" aria-controls="home" role="tab">
                        <i class="fa fa-ruble"></i> Цены
                    </a>
                </li>
                <li role="presentation" class="{% if tab == 'photos' %}active{% endif %}">
                    <a href="{% url 'hotel:property_photo_list' property.id %}" aria-controls="home" role="tab">
                        <i class="fa fa-photo"></i> Фото
                    </a>
                </li>
            </ul>

        {% endblock %}

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active margin-top-md-lg">
                    {% block hotel_content %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

hotels/templates/hotels/room_form.html
{% extends property.id|yesno:'hotels/property_tabs.html,hotels/layout.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block tabs %}
    {% with 'prices' as tab %}{{ block.super }}{% endwith %}
{% endblock tabs %}

{% block hotel_content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success margin-right-sm">
            <i class="fa fa-check-circle-o"></i><span class="margin-left-sm">
            {{ room.id|yesno:'Обновить, Добавить' }} цену</span>
        </button>
        <a href="{% url 'hotel:property_room_list' property.id %}" class="btn btn-default">
            <i class="fa fa-ban"></i><span class="hidden-xs margin-left-sm">Отмена</span>
        </a>
    </form>
{% endblock %}

hotels/templates/hotels/room_list.html
{% extends 'hotels/property_tabs.html' %}
{% load staticfiles %}
{% load main %}
{% load i18n %}
{% load humanize %}
{% block tabs %}
    {% with 'prices' as tab %}{{ block.super }}{% endwith %}
{% endblock tabs %}

{% block hotel_content %}
    {% if rooms|length %}
        <table class="table table-hover table-striped" id="property-table">
            {% for room in rooms %}
                <tr>
                    <td>
                        <a href="{% url 'hotel:property_room_change' room.id %}"
                           class="btn btn-success btn-sm pull-right action" data-toggle="tooltip"
                           data-placement="left"
                           title="Перейти к редактированию цены">
                            <i class="fa fa-pencil"></i>
                        </a>

                        <h3>
                            <a href="{% url 'hotel:property_room_change' room.id %}" data-toggle="tooltip"
                               data-placement="top" title="Перейти к редактированию цены">
                                {{ room }}
                                -
                                <small class="margin-left-sm text-success">{{ room.price|intcomma }}
                                    р. {{ room.get_calculation_type_display|lower }}</small>
                            </a>
                        </h3>
                        <p class="text-muted font-lg">
                            <small><i class="fa fa-male margin-right-sm"></i></small>
                            {{ room.get_gender_display }} на {{ room.places }} мест{{ room.places|ru_pluralize:'о,а,' }}
                        </p>
                        <small class="text-muted">
                            {{ room.description|truncatechars:800|linebreaks }}
                        </small>

                        {% if not room.is_enabled %}
                            <p class="text-danger">
                                <strong>
                                    <i class="fa fa-exclamation-circle"></i>
                                    Цена выключена.
                                    Перейти к <a href="{% url 'hotel:property_room_change' room.id %}">редактированию
                                    цены?</a>
                                </strong>
                            </p>
                        {% endif %}

                    </td>
                </tr>
            {% endfor %}
        </table>

        <p class="text-center margin-top-md-lg">
            <a href="{% url 'hotel:property_room_create' property.id %}" class="btn btn-primary">
                <i class="fa fa-plus"></i> Добавить новую цену
            </a>
        </p>
    {% else %}
        <div class="alert alert-warning">
            <i class="fa fa-exclamation-circle margin-right-xs"></i>
            Не заполнена ни одна цена у отеля. <a href="{% url 'hotel:property_room_create' property.id %}">Добавить первую?</a>
        </div>
    {% endif %}
    {% with tariff=property.get_tariff %}
        {% if tariff %}
            <div class="alert  bg-gray disabled color-palette" id="commission-list">
                <p><i class="fa fa-info-circle margin-right-xs"></i> Комисссия HostelHunt:</p>
                <small>
                    <ul>
                        {% for price in tariff.tariffelement_set.all %}
                            <li>Сумма от {{ price.start_sum }} р. до {{ price.end_sum }} р. - {{ price.commission }}%
                            </li>
                        {% endfor %}
                        <li>Минимальная комисссия - {{ tariff.minimal_commission }} p.</li>
                    </ul>
                </small>
            </div>
        {% endif %}
    {% endwith %}
{% endblock %}